version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build    # compiles server/ → dist-server/
      - echo "web: npm start" > Procfile
artifacts:
  files:
    - package.json
    - package-lock.json
    - Procfile
    - dist-server/**/*      # include compiled code
  discard-paths: no
