version: 0.2

phases:
  install:
    commands:
      - npm ci || npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - dist-server//* 
    - public//* 
    - buildspec-test.yml 
    - Procfile
  discard-paths: no



# version: 0.2

# phases:
#   install:
#     commands:
#       - npm ci
#   build:
#     commands:
#       - npm run build
#       - 'printf "web: npm start\n" > Procfile'

# artifacts:
#   files:
#     - package.json
#     - package-lock.json
#     - Procfile
#     - dist-server/**/*
#   discard-paths: no

